### ISSUE TITLE
qbatch error 

### ISSUE THREAD

**Issue by neer86upadhyay** [CoBrALab/antsRegistration-MAGeT#102]
Dear Gabriel, 
When we tried running the MAgetbrain on our system MAC mojave 10.14. We got following error in running the qbtach.
qbatch: error: local run call returned error code 15
Traceback (most recent call last):
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 792, in <module>
    main()
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 220, in main
    options.func(options)
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 329, in command_run
    p.run()
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 608, in run
    self.queue.run(stages=self._get_stage_order())
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 539, in run
    processors=processors)
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 559, in qbatch
    opt_afterok, opt_batchsize, opt_walltime), input='\n'.join(commands))
  File "/Users/Angelika/Documents/Test/Habenula/MAGeTbrain/bin/mb", line 492, in execute
    raise Exception("Returns %i :: %s" % (proc.returncode, command))
Exception: Returns 1 :: qbatch --jobname mb_templatelib_2021-03-02T15-20-20 --depend NONE* --chunksize 8 --walltime 6:00:00 -

Plesae have a look and guide us How it can be solved. 

Best Wishes, 
Neeraj

**Comment by gdevenyi** [comment]
Have you configured your qbatch? What is the output of `printenv | grep QBATCH`

**Comment by gdevenyi** [comment]
Please use the proper repository to report issues. https://github.com/CoBrALab/MAGeTbrain
